### ISSUE TITLE
Не обрабатываются фото не в html

### ISSUE THREAD

**Issue by Antevea** [akstyr/RaisRun#1]
Фото во внутренних файлах не отображаются на странице.
Поможет указание мне на их место в коде или перенос их в корневой файл html.
Список файлов:
/img/slider-fon_5.jpg
/favicon.ico

**Comment by mariaigorevna** [comment]
/img/slider-fon_5.jpg : в коде css\style.css 146 строчка кода
/favicon.ico : такой элемент отсутствует в проекте

**Comment by Antevea** [comment]
Thank u for your answer! :+1:  I will fix it very soon.
